package mesko.matus.ui;

import javax.swing.JButton;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Custom button with arrow appearance for navigation
 * GENERATED BY AI
 */
public class ArrowButton extends JButton {

    /**
     * Creates a styled arrow button with image background
     * @param direction "left" or "right" to specify which arrow image to load
     */
    public ArrowButton(String direction) {
        super();
        this.setFocusPainted(false);
        this.setBorderPainted(false);
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.setContentAreaFilled(false);

        try {
            String imagePath = "/" + direction + ".png";
            ImageIcon arrowIcon = new ImageIcon(getClass().getResource(imagePath));
            this.setIcon(arrowIcon);
            this.setPreferredSize(new Dimension(arrowIcon.getIconWidth(), arrowIcon.getIconHeight()));
        } catch (Exception e) {
            System.err.println("Could not load " + direction + " arrow image: " + e.getMessage());
            this.setText(direction.equals("left") ? "<" : ">");
            this.setFont(new Font("Arial", Font.BOLD, 24));
            this.setForeground(Color.WHITE);
            this.setBackground(new Color(139, 69, 19)); // Brown color
            this.setContentAreaFilled(true);
        }

        this.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                setForeground(new Color(255, 215, 0));
            }

            public void mouseExited(MouseEvent evt) {
                ArrowButton.this.setForeground(Color.WHITE);
            }
        });
    }
}